credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: github
          username: root
          password: root
          description: "Git Login"

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
        - id: developer
          password: developer

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Job/Build:developer"
        - "Job/Cancel:developer"

  remotingSecurity:
    enabled: true

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: http://server_ip:8080/

unclassified:
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.jsdelivr.net/gh/afonsof/jenkins-material-theme@gh-pages/dist/material-cyan.css"

jobs:
  - file: /usr/local/seedjob.groovy

jobs:
  - script: >
      pipelineJob('pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Fat-Frumos/Lab.git')
                }
                branches('*/developer')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }
